AllCops:
  NewCops: enable

require:
  - rubocop-rspec

Metrics/BlockLength:
  Exclude:
    - spec/**/*

RSpec/MultipleExpectations:
  Exclude:
    - spec/**/*

RSpec/VerifiedDoubles:
  Exclude:
    - spec/**/*

RSpec/ExampleLength:
  Max: 20